version: '3.5'

services:
  nginx:
    image: nginx:1.16.0
    restart: always
    ports:
      - '8081:80'
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./config/nginx/conf.d/:/etc/nginx/conf.d:ro
      - ./config/nginx/www/:/var/www:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/colon/IS/S14-327/:/img/:ro

